# Generated by Django 4.0.5 on 2022-07-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EverydayLife', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=100)),
                ('nihongo', models.CharField(max_length=100)),
            ],
        ),
    ]
