# Generated by Django 4.0.5 on 2022-07-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_alter_qdata_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=10000)),
                ('end', models.CharField(max_length=10000)),
            ],
        ),
    ]
