# Generated by Django 4.0.5 on 2022-07-14 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_sheetcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanjiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.CharField(max_length=100)),
                ('eigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Nihongo', to='Quiz.qdata')),
            ],
        ),
    ]
