# Generated by Django 4.0.5 on 2022-07-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_kanjidata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eigo', models.CharField(max_length=10000)),
                ('nihongo', models.CharField(max_length=10000)),
            ],
        ),
    ]
