# Generated by Django 4.0.5 on 2022-07-15 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='eigo',
            new_name='english',
        ),
    ]
