# Generated by Django 4.0.5 on 2022-07-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_rename_eigo_question_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='e_negative',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='e_positive',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='n_negative',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='n_positive',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
