# Generated by Django 4.0.5 on 2022-07-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_question_e_negative_question_e_positive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='e_negative',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='e_positive',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='n_negative',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='n_positive',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
