# Generated by Django 4.0.5 on 2022-07-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0009_alter_question_e_negative_alter_question_e_positive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QData2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=100)),
                ('nihongo', models.CharField(max_length=100)),
            ],
        ),
    ]
