# Generated by Django 4.0.5 on 2022-09-19 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='N4L',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=100)),
                ('nihongo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KanjiN4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.CharField(max_length=100)),
                ('eigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Nihongo', to='N4_Voc.n4l')),
            ],
        ),
    ]
