# Generated by Django 4.0.5 on 2022-07-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerbData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_form', models.CharField(max_length=50)),
                ('present_positive', models.CharField(max_length=50)),
                ('present_negative', models.CharField(max_length=50)),
                ('past_positive', models.CharField(max_length=50)),
                ('past_negative', models.CharField(max_length=50)),
                ('te_from', models.CharField(max_length=50)),
                ('present_continuous', models.CharField(max_length=50)),
                ('past_continuous', models.CharField(max_length=50)),
            ],
        ),
    ]
