# Generated by Django 4.0.5 on 2022-07-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Verb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verbdata',
            name='english',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
